name: Acceptance Tests

on:
  pull_request:
    branches: [main, release/**]
  push:
    branches: [main, release/**]
    tags: [v*]

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  api_batch_3:
    name: API Batch 3
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: api_batch3
