name: Acceptance Tests

on:
  pull_request:
    branches: [main, release/**]
  push:
    branches: [main, release/**]
    tags: [v*]

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  api_batch_1:
    name: API Batch 1
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: api_batch1

  api_batch_2:
    name: API Batch 2
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: api_batch2

  api_batch_3:
    name: API Batch 3
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: api_batch3

  erc20:
    name: ERC20
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: erc20

  ratelimiter:
    name: Rate Limiter
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: ratelimiter
      test_ws_server: true

  hbarlimiter_batch_1:
    name: HBar Limiter Batch 1
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: hbarlimiter_batch1

  hbarlimiter_batch_2:
    name: HBar Limiter Batch 2
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: hbarlimiter_batch2

  hbarlimiter_batch_3:
    name: HBar Limiter Batch 3
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: hbarlimiter_batch3

  tokencreate:
    name: Token Create
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: tokencreate

  tokenmanagement:
    name: Token Management
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: tokenmanagement

  htsprecompilev1:
    name: Precompile
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: htsprecompilev1

  precompilecalls:
    name: Precompile Calls
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: precompile-calls

  websocket-batch-1:
    name: Websocket Batch 1
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: ws_batch1
      test_ws_server: true

  websocket-batch-2:
    name: Websocket Batch 2
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: ws_batch2
      test_ws_server: true

  websocket-batch-3:
    name: Websocket Batch 3
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: ws_batch3
      test_ws_server: true

  cacheservice:
    name: Cache Service
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: cache-service

  server-config:
    name: Server Config
    uses: ./.github/workflows/acceptance-workflow.yml
    with:
      testfilter: serverconfig
