name: Reusable acceptance tests workflow

on:
  workflow_call:
    inputs:
      testfilter:
        required: true
        type: string
      test_ws_server:
        required: false
        default: false
        type: boolean
      envfile:
        required: false
        default: localAcceptance.env
        type: string
      operator_id:
        required: false
        type: string
      networkTag:
        required: false
        type: string
      mirrorTag:
        required: false
        type: string
      relayTag:
        required: false
        type: string
      maxAttempts:
        required: false
        type: number
        default: 3
    secrets:
      operator_key:
        description: 'The ED25519, ECDSA, or DER encoded private key of the operator'
        required: false

env:
  OPERATOR_ID_MAIN: ${{ inputs.operator_id }}

jobs:
  acceptance-workflow:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    permissions:
      contents: read
      actions: read
      checks: write
      # issues: read
    env:
      OPERATOR_ID_MAIN: ${{ inputs.operator_id }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20

      - name: Install make
        run: sudo apt-get update; sudo apt-get install build-essential -y

      - name: Checkout repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install packages
        run: npm ci

      - name: Create .env file
        run: cp ./packages/server/tests/${{ inputs.envfile }} .env

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build Typescript
        run: npx lerna run build

      - name: Install hedera local
        run: npm install @hashgraph/hedera-local -g

      - name: Run hedera local
        run: npx hedera restart -d --verbose=trace --network-tag=${{ inputs.networkTag }} --mirror-tag=${{ inputs.mirrorTag }}

      - name: Stop relay
        run: docker stop json-rpc-relay json-rpc-relay-ws

      - name: Run acceptance tests
        env:
          TEST_WS_SERVER: ${{ inputs.test_ws_server }}
          SUBSCRIPTIONS_ENABLED: ${{ inputs.test_ws_server }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUMBER: ${{ github.event.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          OPERATOR_KEY_MAIN: 302e020100300506032b65700422042091132178e72057a1d7528025956fe39b0b847f200ab59b2fdd367017f3087137
        run: |
          echo "Running acceptance tests..."
          echo "Max attempts: ${{ inputs.maxAttempts }}"
          echo "Test filter: ${{ inputs.testfilter }}"
          npm run acceptancetest:${{ inputs.testfilter }}
